# WEB PROPERTIES
server:
  #address: 192.168.1.32
  port: 8080

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: 'oracle.jdbc.OracleDriver'
    url: 'jdbc:oracle:thin:@192.168.1.156:1521/xgsid.xg156.com'
    username: 'ESTAR'
    password: 'ESTAR'

  # redis
  redis:
    database: 11
    host: 192.168.1.156
    port: 6379